#!/bin/bash


ZMPROV="/opt/zimbra/bin/zmprov"
ZMCONTROL="/opt/zimbra/bin/zmcontrol"
ZMMAILBOX="/opt/zimbra/bin/zmmailbox"
HOST1=$(grep server1 server  | awk -F= '{print $2}')
HOST2=$(grep server2 server  | awk -F= '{print $2}')
PASS1=$(grep password1 server  | awk -F= '{print $2}')
PASS2=$(grep password2 server  | awk -F= '{print $2}')
CONNECT="ssh -i rabbit.pem root@$HOST1"
TRANSFER="scp -i rabbit.pem root@$HOST1"


DIRTMPSHARED="/tmp/shared_folder"
for USERDEST in $(cat users) ; do 

#   LISTAR PASTAS COMPARTILHADAS NA CONTA
ZMLISTFOLDER="$ZMMAILBOX -z -m ${USERDEST} gaf | grep \) | sed 's/:/|/g' | sed 's/ (/|/g' | sed 's/)/|/g' | awk -F/ '{print \"/\"\$2}' "

  $CONNECT $ZMLISTFOLDER > ${DIRTMPSHARED}_${USERDEST}

FINDTEXT="cat ${DIRTMPSHARED}_${USERDEST}"

 if [ -z "$FINDTEXT" ]; then  

echo " User ${USERDEST} does not has shared folder "

else 
    for FOLDERID in $(awk -F"|" '{print $3}' ${DIRTMPSHARED}_${USERDEST}) ; do
        ZMFILTERFILE="$ZMMAILBOX -z -m $(grep -w  ${FOLDERID} ${DIRTMPSHARED}_${USERDEST} |cut -d"|" -f2 ) gaf |  awk -F/ ' \$1 ~ /$FOLDERID/ {print \"/\"\$2}'"

        FOLDERDEST=$(grep -w  $FOLDERID ${DIRTMPSHARED}_${USERDEST} | awk -F"|" '{print $1}')
        USERORIG=$(grep -w  $FOLDERID ${DIRTMPSHARED}_${USERDEST} | awk -F"|" '{print $2}')

        TRADEID=$($CONNECT $ZMFILTERFILE)
        sed -i "s~${FOLDERID}~${TRADEID}~" ${DIRTMPSHARED}_${USERDEST}

        FOLDERORIG=$(grep  -w ${TRADEID} ${DIRTMPSHARED}_${USERDEST} | awk -F"|" '{print $3}' )

        $ZMMAILBOX -z -m ${USERDEST} df "$FOLDERDEST"


        $ZMMAILBOX -z -m $USERORIG mfg "$TRADEID" account ${USERDEST} rwixa
        $ZMMAILBOX -z -m ${USERDEST} cm "$FOLDERDEST" $USERORIG  "$TRADEID"

    done
fi 

done 


